name: Gradle build and docker package

on:
  workflow_call:
    inputs:
      acr-name:
        required: true
        type: string
    secrets:
      external-maven-repo-password:
        required: true
      acr-username:
        required: true
      acr-password:
        required: true

jobs:
  build:
    name: Gradle build and test.
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        cache: 'gradle'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: |
          build 
          -PexternalPassword=${{ secrets.external-maven-repo-password }}
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: build/libs/*.jar
    - name: Generate gradel properties
      run: ./gradlew properties -q > build/gradle_props.yml
    - name: Upload gradle properties
      uses: actions/upload-artifact@v3
      with:
        name: gradle-props
        path: build/gradle_props.yml
  image-build:
    name: Build docker image and push
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Dowaload build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-artifacts
    - name: Dowaload gradle props
      uses: actions/download-artifact@v3
      with:
        name: gradle-props
    - name: Set image name
      run: echo "IMAGE=${{ inputs.acr-name }}.azurecr.io/${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
    - name: Set image version by tag
      run: echo "IMAGE_VERSION=$GITHUB_REF_NAME" >> $GITHUB_ENV
      if: github.ref.type == 'tag'
    - name: Set image version by property
      run: echo "IMAGE_VERSION=$(grep "^version:" gradle_props.yml | awk '{print $2}' | tr -d '[:space:]')" >> $GITHUB_ENV
      if: github.ref.type != 'tag'
    - name: Login azure container registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ inputs.acr-name }}.azurecr.io
        username: ${{ secrets.acr-username }}
        password: ${{ secrets.acr-password }}
    - name: Build and push docker images
      run: |        
        docker build . -t $IMAGE:$IMAGE_VERSION -t $IMAGE:latest --no-cache --build-arg JAR_FILE=build/libs/*.jar
        docker push  $IMAGE:$IMAGE_VERSION
        docker push  $IMAGE:latest


    
    
    
