name: Deploy to aks

on:
  workflow_call:
    inputs:
      deploy-to:
        required: true
        type: string
      cluster-name:
        required: true
        type: string
      resource-group:
        required: true
        type: string
      replicas:
        required: true
        type: string
        default: '1'
      version:
        required: true
        type: string
        default: '1'
    secrets:
      AZURE_CREDENTIALS:
        required: true
jobs:
  deploy:
    name: Deploy to ${{ inputs.deploy-to }}
    runs-on: ubuntu-latest
    steps:
    - uses: emersonsoftware/checkout@v2
    - name: update replicas
      run: |
        sed -i 's/@replicas@/${{ inputs.replicas }}/g' k8s.yaml
        sed -i 's/@version@/replicas: ${{ inputs.version }}/g' k8s.yaml

    # Set the target Azure Kubernetes Service (AKS) cluster.
    - uses: emersonsoftware/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ inputs.cluster-name }}
        resource-group: ${{ inputs.resource-group }}
      # Deploy app to AKS
    - uses: emersonsoftware/k8s-deploy@v1
      with:
        manifests: k8s.yaml
