name: Gradle build test and sonar scan

on:
  workflow_call:
    secrets:
      EXTERNAL_PASSWORD:
        required: true
jobs:
  build:
    name: Gradle build, test and sonar scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        cache: 'gradle'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: |
          build  
          publish 
          -PexternalPassword=${{ secrets.EXTERNAL_PASSWORD }}
