name: Gradle build test and sonar scan

on:
  workflow_call:
    secrets:
      external-maven-repo-password:
        required: true
      sonar-token:
        required: true
      GITHUB_TOKEN:
        required: true
jobs:
  build:
    name: Gradle build, test and sonar scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        cache: 'gradle'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      env: 
        SONAR_TOKEN: ${{ secrets.sonar-token }}
        SONAR_HOST_URL: https://sonarcloud.io
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        arguments: build sonarqube -PexternalPassword=${{ secrets.external-maven-repo-password }}
