name: Set environment variable

on:
  workflow_call:
    inputs:
      env-name:
        required: true
        type: string
      env-json:
        required: true
        type: string
    outputs:
      deploy-to:
        description: "Target environment to deploy"
        value: ${{ jobs.set-params.outputs.deploy-to }}
      cluster-name:
        description: "Cluster name"
        value: ${{ jobs.set-params.outputs.cluster-name }}
      resource-group:
        description: "Resource group"
        value: ${{ jobs.set-params.outputs.resource-group }}
      cred-prefix:
        description: "azure credential prefix"
        value: ${{ jobs.set-params.outputs.azure-credentials }}
jobs:
  set-params:
    runs-on: ubuntu-latest
    outputs:
      deploy-to: ${{ steps.setValue.outputs.deploy-to }}
      cluster-name: ${{ steps.setValue.outputs.cluster-name }}
      resource-group: ${{ steps.setValue.outputs.resource-group }}
      azure-credentials: ${{ steps.setCredentials.outputs.azure-credentials }}
    steps:
      - id: setValue
        name: set values for ${{ inputs.env-name }}
        run: |
          echo input is '${{ toJson(fromJson(inputs.env-json)[inputs.env-name]) }}'
          ENVJSON = ${{ fromJson(inputs.env-json)[inputs.env-name] }}
          if ${{ inputs.env-name =='staging'}}
            ENVJSON.cred-prefix="STAGING"
          else
            ENVJSON.cred-prefix="PROD"
          fi
          echo '::set-output name=deploy-to::$EVNJSON }}'
          echo ::set-output name=cluster-name::${{ fromJson(inputs.env-json)[inputs.env-name].cluster-name }}
          echo ::set-output name=resource-group::${{ fromJson(inputs.env-json)[inputs.env-name].resource-group }}

      - id: setCredentials
        name: set credentials for ${{ inputs.env-name }}
        run: |
          if ${{ inputs.env-name =='staging'}}
          then
            echo 'setting staging'
            echo '::set-output name=azure-credentials::STAGING'
          else
            echo 'setting staging'
            echo '::set-output name=azure-credentials::PROD'
          fi