name: Set environment variable

on:
  workflow_call:
    inputs:
      env-name:
        required: true
        type: string
      env-json:
        required: true
        type: string
    secrets:
      credentials:
        required: true
jobs:
  set-params:
    runs-on: ubuntu-latest
    outputs:
      env-json: ${{ steps.setValue.outputs.env-json }}
      azure-credentials: ${{ steps.setCredentials.outputs.azure-credentials }}
    steps:
      - id: setValue
        name: set values for ${{ inputs.env-name }}
        run: |
          echo 'input is ${{ inputs.env-json }}'
          echo "::set-output name=env-json::${{ toJson(fromJson(inputs.env-json)[inputs.env-name]) }}"
      - id: setCredentials
        name: set credentials for ${{ inputs.env-name }}
        run: |
          echo ${{ fromJson(secrets.credentials)[inputs.env-name] }} | sed 's/./& /g'
          echo "::set-output name=azure-credentials::${{ fromJson(inputs.env-json)[inputs.env-name] }}"