name: Set environment variable

on:
  workflow_call:
    inputs:
      env-name:
        required: true
        type: string
      env-json:
        required: true
        type: string
    secrets:
      credentails:
        required: true
jobs:
  set-params:
    runs-on: ubuntu-latest
    outputs:
      env-json: ${{ steps.setValue.outputs.env-json }}
      azure-credentials: ${{ steps.setValue.outputs.azure-credentials }}
    steps:
      - id: setValue
        name: set values for ${{ inputs.env-name }}
        run: |
          echo ${{ toJson(fromJson(inputs.env-json)[inputs.env-name]) }}'
          echo '::set-output name=env-json::${{ toJson(fromJson(inputs.env-json)[inputs.env-name]) }}'
          echo ${{ fromJson(secrets.credentails)[inputs.env-name] }}
          echo '::set-output name=azure-credentials::${{ fromJson(secrets.credentails)[inputs.env-name] }}'
